In [67]:
import numpy as np
import pandas as pd

In [68]:
datos = pd.read_csv("combined_summary_k_pneumoniae.csv", sep=";", index_col=0)
datos

,A7J11_01233+.assembled,A7J11_01233+.ref_seq,A7J11_01233+.pct_id,A7J11_01233+.ctg_cov,aac_3__II-.assembled,aac_3__II-.ref_seq,aac_3__II-.pct_id,aac_3__II-.ctg_cov,aac_6___Ib+.assembled,aac_6___Ib+.ref_seq,...,ompK36.N304E,ompK36.N49S,ompK36.S346N,ompK36.T222L,ompK37.assembled,ompK37.E244D,ompK37.I128M,ompK37.I70M,ompK37.N230G,ramR.assembled
name,,,,,,,,,,,,,,,,,,,,,
KPN12_S2_L001,partial,A7J11_01233.NG_047213.1,99.83,51.8,no,NaN,NaN,NaN,yes,aac_6___Ib.NG_056043.1,...,yes,yes,yes,no,yes,yes,yes,yes,yes,yes
KPN13_S3_L001,partial,A7J11_01233.NG_047213.1,99.65,37.7,no,NaN,NaN,NaN,yes,aac_6___Ib4.NG_051844.1,...,no,yes,no,no,yes,no,yes,yes,no,interrupted
KPN14_S4_L001,no,NaN,NaN,NaN,no,NaN,NaN,NaN,no,NaN,...,yes,yes,yes,yes,yes,no,yes,yes,no,interrupted
KPN15_S5_L001,partial,A7J11_01233.NG_047213.1,99.83,82.3,yes_nonunique,aac_3__IId.NG_047251.1,100.00,98.8,yes_nonunique,aac_6___Ib.NG_056043.1,...,no,yes,yes,no,yes,no,yes,yes,no,interrupted
KPNH_S7_L001,partial,A7J11_01233.NG_047213.1,99.83,35.9,no,NaN,NaN,NaN,yes,aac_6___Ib.NG_056043.1,...,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes
KPNI_S8_L001,partial,A7J11_01233.NG_047213.1,99.65,30.3,partial,aac_3__IId.NG_047251.1,99.76,2.0,yes,aac_6___Ib4.NG_051844.1,...,no,yes,no,no,yes,no,yes,yes,no,interrupted
KPNJ_S2_L001,no,NaN,NaN,NaN,no,NaN,NaN,NaN,no,NaN,...,yes,yes,yes,yes,yes,no,yes,yes,no,interrupted
KPNK_S1_L001,partial,A7J11_01233.NG_047213.1,99.83,111.8,yes_nonunique,aac_3__IId.NG_047251.1,100.00,151.5,yes_nonunique,aac_6___Ib.NG_056043.1,...,no,yes,no,no,yes,no,yes,yes,no,interrupted

In [69]:
datos=datos.rename_axis('samples')
datos

,A7J11_01233+.assembled,A7J11_01233+.ref_seq,A7J11_01233+.pct_id,A7J11_01233+.ctg_cov,aac_3__II-.assembled,aac_3__II-.ref_seq,aac_3__II-.pct_id,aac_3__II-.ctg_cov,aac_6___Ib+.assembled,aac_6___Ib+.ref_seq,...,ompK36.N304E,ompK36.N49S,ompK36.S346N,ompK36.T222L,ompK37.assembled,ompK37.E244D,ompK37.I128M,ompK37.I70M,ompK37.N230G,ramR.assembled
samples,,,,,,,,,,,,,,,,,,,,,
KPN12_S2_L001,partial,A7J11_01233.NG_047213.1,99.83,51.8,no,NaN,NaN,NaN,yes,aac_6___Ib.NG_056043.1,...,yes,yes,yes,no,yes,yes,yes,yes,yes,yes
KPN13_S3_L001,partial,A7J11_01233.NG_047213.1,99.65,37.7,no,NaN,NaN,NaN,yes,aac_6___Ib4.NG_051844.1,...,no,yes,no,no,yes,no,yes,yes,no,interrupted
KPN14_S4_L001,no,NaN,NaN,NaN,no,NaN,NaN,NaN,no,NaN,...,yes,yes,yes,yes,yes,no,yes,yes,no,interrupted
KPN15_S5_L001,partial,A7J11_01233.NG_047213.1,99.83,82.3,yes_nonunique,aac_3__IId.NG_047251.1,100.00,98.8,yes_nonunique,aac_6___Ib.NG_056043.1,...,no,yes,yes,no,yes,no,yes,yes,no,interrupted
KPNH_S7_L001,partial,A7J11_01233.NG_047213.1,99.83,35.9,no,NaN,NaN,NaN,yes,aac_6___Ib.NG_056043.1,...,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes
KPNI_S8_L001,partial,A7J11_01233.NG_047213.1,99.65,30.3,partial,aac_3__IId.NG_047251.1,99.76,2.0,yes,aac_6___Ib4.NG_051844.1,...,no,yes,no,no,yes,no,yes,yes,no,interrupted
KPNJ_S2_L001,no,NaN,NaN,NaN,no,NaN,NaN,NaN,no,NaN,...,yes,yes,yes,yes,yes,no,yes,yes,no,interrupted
KPNK_S1_L001,partial,A7J11_01233.NG_047213.1,99.83,111.8,yes_nonunique,aac_3__IId.NG_047251.1,100.00,151.5,yes_nonunique,aac_6___Ib.NG_056043.1,...,no,yes,no,no,yes,no,yes,yes,no,interrupted

In [70]:
#####------------------>>>>>>> mutaciones de genes

df_assembled = datos[datos.columns.drop(list(datos.filter(regex='.assembled')))]
df_ref_seq = df_assembled[df_assembled.columns.drop(list(df_assembled.filter(regex='.ref_seq')))]
df_pct_id = df_ref_seq[df_ref_seq.columns.drop(list(df_ref_seq.filter(regex='.pct_id')))]
mutations = df_pct_id[df_pct_id.columns.drop(list(df_pct_id.filter(regex='.ctg_cov')))]
mutations

,known_variants,acrR.F172S,acrR.F197I,acrR.G164A,acrR.K201M,acrR.L195V,acrR.P161R,acrR.R173G,gyrA.D87G,ompK36.A183P,...,ompK36.L59V,ompK36.N218H,ompK36.N304E,ompK36.N49S,ompK36.S346N,ompK36.T222L,ompK37.E244D,ompK37.I128M,ompK37.I70M,ompK37.N230G
samples,,,,,,,,,,,,,,,,,,,,,
KPN12_S2_L001,NaN,yes,yes,yes,yes,yes,yes,yes,no,no,...,yes,no,yes,yes,yes,no,yes,yes,yes,yes
KPN13_S3_L001,NaN,yes,yes,yes,yes,yes,yes,yes,no,yes,...,yes,yes,no,yes,no,no,no,yes,yes,no
KPN14_S4_L001,NaN,yes,yes,yes,yes,yes,yes,yes,no,no,...,yes,no,yes,yes,yes,yes,no,yes,yes,no
KPN15_S5_L001,NaN,yes,yes,yes,yes,yes,yes,yes,NaN,no,...,yes,yes,no,yes,yes,no,no,yes,yes,no
KPNH_S7_L001,NaN,yes,yes,yes,yes,yes,yes,yes,no,no,...,yes,no,yes,yes,yes,yes,yes,yes,yes,yes
KPNI_S8_L001,NaN,yes,yes,yes,yes,yes,yes,yes,no,yes,...,yes,yes,no,yes,no,no,no,yes,yes,no
KPNJ_S2_L001,NaN,yes,yes,yes,yes,yes,yes,yes,no,no,...,yes,no,yes,yes,yes,yes,no,yes,yes,no
KPNK_S1_L001,NaN,yes,yes,yes,yes,yes,yes,yes,yes,no,...,yes,yes,no,yes,no,no,no,yes,yes,no

In [71]:
mutations_yes=mutations[mutations=="yes"]
mutations_yes

/Users/felipedb/opt/anaconda3/envs/agrosavia/lib/python3.7/site-packages/pandas/core/ops/array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)

,known_variants,acrR.F172S,acrR.F197I,acrR.G164A,acrR.K201M,acrR.L195V,acrR.P161R,acrR.R173G,gyrA.D87G,ompK36.A183P,...,ompK36.L59V,ompK36.N218H,ompK36.N304E,ompK36.N49S,ompK36.S346N,ompK36.T222L,ompK37.E244D,ompK37.I128M,ompK37.I70M,ompK37.N230G
samples,,,,,,,,,,,,,,,,,,,,,
KPN12_S2_L001,NaN,yes,yes,yes,yes,yes,yes,yes,NaN,NaN,...,yes,NaN,yes,yes,yes,NaN,yes,yes,yes,yes
KPN13_S3_L001,NaN,yes,yes,yes,yes,yes,yes,yes,NaN,yes,...,yes,yes,NaN,yes,NaN,NaN,NaN,yes,yes,NaN
KPN14_S4_L001,NaN,yes,yes,yes,yes,yes,yes,yes,NaN,NaN,...,yes,NaN,yes,yes,yes,yes,NaN,yes,yes,NaN
KPN15_S5_L001,NaN,yes,yes,yes,yes,yes,yes,yes,NaN,NaN,...,yes,yes,NaN,yes,yes,NaN,NaN,yes,yes,NaN
KPNH_S7_L001,NaN,yes,yes,yes,yes,yes,yes,yes,NaN,NaN,...,yes,NaN,yes,yes,yes,yes,yes,yes,yes,yes
KPNI_S8_L001,NaN,yes,yes,yes,yes,yes,yes,yes,NaN,yes,...,yes,yes,NaN,yes,NaN,NaN,NaN,yes,yes,NaN
KPNJ_S2_L001,NaN,yes,yes,yes,yes,yes,yes,yes,NaN,NaN,...,yes,NaN,yes,yes,yes,yes,NaN,yes,yes,NaN
KPNK_S1_L001,NaN,yes,yes,yes,yes,yes,yes,yes,yes,NaN,...,yes,yes,NaN,yes,NaN,NaN,NaN,yes,yes,NaN

In [72]:
mutations_st=mutations_yes.stack()
mutations_st

samples
KPN12_S2_L001  acrR.F172S      yes
               acrR.F197I      yes
               acrR.G164A      yes
               acrR.K201M      yes
               acrR.L195V      yes
                              ...
KPNK_S1_L001   ompK36.L59V     yes
               ompK36.N218H    yes
               ompK36.N49S     yes
               ompK37.I128M    yes
               ompK37.I70M     yes
Length: 153, dtype: object

In [73]:
#####------------------->>>>>>>> mutation dataframe final result
mutations_yes=pd.DataFrame(mutations_st)
mutation_result_df=mutations_yes.rename(columns = {0:'mutation_result'}, inplace = False)
mutation_result_df

                           mutation_result
samples
KPN12_S2_L001 acrR.F172S               yes
              acrR.F197I               yes
              acrR.G164A               yes
              acrR.K201M               yes
              acrR.L195V               yes
...                                    ...
KPNK_S1_L001  ompK36.L59V              yes
              ompK36.N218H             yes
              ompK36.N49S              yes
              ompK37.I128M             yes
              ompK37.I70M              yes

[153 rows x 1 columns]

In [80]:
mutation_result_df = mutation_result_df.reset_index(level=[0,1])
mutation_result_df

           samples       level_1 mutation_result
0    KPN12_S2_L001    acrR_F172S             yes
1    KPN12_S2_L001    acrR_F197I             yes
2    KPN12_S2_L001    acrR_G164A             yes
3    KPN12_S2_L001    acrR_K201M             yes
4    KPN12_S2_L001    acrR_L195V             yes
..             ...           ...             ...
148   KPNK_S1_L001   ompK36_L59V             yes
149   KPNK_S1_L001  ompK36_N218H             yes
150   KPNK_S1_L001   ompK36_N49S             yes
151   KPNK_S1_L001  ompK37_I128M             yes
152   KPNK_S1_L001   ompK37_I70M             yes

[153 rows x 3 columns]

In [81]:
mutation_result_df=mutation_result_df.stack().str.replace('.','_').unstack()

In [82]:
mutation_result_df=mutation_result_df.set_index(['samples', 'level_1'])
mutation_result_df

                           mutation_result
samples       level_1
KPN12_S2_L001 acrR_F172S               yes
              acrR_F197I               yes
              acrR_G164A               yes
              acrR_K201M               yes
              acrR_L195V               yes
...                                    ...
KPNK_S1_L001  ompK36_L59V              yes
              ompK36_N218H             yes
              ompK36_N49S              yes
              ompK37_I128M             yes
              ompK37_I70M              yes

[153 rows x 1 columns]

In [83]:
####----------------------------------->>> .assembled process

assembled=datos.columns.str.find(".assembled")

In [84]:
AS=assembled != -1
AS

array([ True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False,  True])

In [85]:
asd=datos.iloc[:,AS]
asd

,A7J11_01233+.assembled,aac_3__II-.assembled,aac_6___Ib+.assembled,aadA-.assembled,aadA1+.assembled,aadA2+.assembled,ant_2____Ia.assembled,aphA16.assembled,aph_3___Ia.assembled,aph_3___XV.assembled,...,qnrS-.assembled,sat2+.assembled,sul1.assembled,sul2.assembled,tet_C_.assembled,acrR.assembled,gyrA.assembled,ompK36.assembled,ompK37.assembled,ramR.assembled
samples,,,,,,,,,,,,,,,,,,,,,
KPN12_S2_L001,partial,no,yes,no,no,yes_nonunique,no,no,yes,no,...,no,no,yes,no,no,yes,partial,partial,yes,yes
KPN13_S3_L001,partial,no,yes,no,no,no,no,no,no,partial,...,yes,no,no,no,no,yes,partial,yes,yes,interrupted
KPN14_S4_L001,no,no,no,no,no,no,no,no,yes,no,...,no,no,yes,no,yes,yes,partial,yes,yes,interrupted
KPN15_S5_L001,partial,yes_nonunique,yes_nonunique,interrupted,yes_nonunique,no,no,no,no,no,...,no,yes,yes,yes,no,yes,no,fragmented,yes,interrupted
KPNH_S7_L001,partial,no,yes,no,no,yes_nonunique,no,no,yes,no,...,no,no,yes,no,no,yes,partial,yes,yes,yes
KPNI_S8_L001,partial,partial,yes,no,partial,no,partial,partial,no,partial,...,yes,no,partial,partial,no,yes,partial,yes,yes,interrupted
KPNJ_S2_L001,no,no,no,no,no,no,no,no,yes,no,...,no,no,yes,no,yes,yes,partial,yes,yes,interrupted
KPNK_S1_L001,partial,yes_nonunique,yes_nonunique,interrupted,yes_nonunique,no,no,no,no,no,...,no,yes,yes,yes,no,yes,partial,partial,yes,interrupted

In [86]:
yes=asd[asd=="yes"]
yes

,A7J11_01233+.assembled,aac_3__II-.assembled,aac_6___Ib+.assembled,aadA-.assembled,aadA1+.assembled,aadA2+.assembled,ant_2____Ia.assembled,aphA16.assembled,aph_3___Ia.assembled,aph_3___XV.assembled,...,qnrS-.assembled,sat2+.assembled,sul1.assembled,sul2.assembled,tet_C_.assembled,acrR.assembled,gyrA.assembled,ompK36.assembled,ompK37.assembled,ramR.assembled
samples,,,,,,,,,,,,,,,,,,,,,
KPN12_S2_L001,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,yes,NaN,...,NaN,NaN,yes,NaN,NaN,yes,NaN,NaN,yes,yes
KPN13_S3_L001,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,yes,NaN,NaN,NaN,NaN,yes,NaN,yes,yes,NaN
KPN14_S4_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,...,NaN,NaN,yes,NaN,yes,yes,NaN,yes,yes,NaN
KPN15_S5_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,yes,yes,yes,NaN,yes,NaN,NaN,yes,NaN
KPNH_S7_L001,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,yes,NaN,...,NaN,NaN,yes,NaN,NaN,yes,NaN,yes,yes,yes
KPNI_S8_L001,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,yes,NaN,NaN,NaN,NaN,yes,NaN,yes,yes,NaN
KPNJ_S2_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,...,NaN,NaN,yes,NaN,yes,yes,NaN,yes,yes,NaN
KPNK_S1_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,yes,yes,yes,NaN,yes,NaN,NaN,yes,NaN

In [87]:
yes_nonunique=asd[asd=="yes_nonunique"]
yes_nonunique

,A7J11_01233+.assembled,aac_3__II-.assembled,aac_6___Ib+.assembled,aadA-.assembled,aadA1+.assembled,aadA2+.assembled,ant_2____Ia.assembled,aphA16.assembled,aph_3___Ia.assembled,aph_3___XV.assembled,...,qnrS-.assembled,sat2+.assembled,sul1.assembled,sul2.assembled,tet_C_.assembled,acrR.assembled,gyrA.assembled,ompK36.assembled,ompK37.assembled,ramR.assembled
samples,,,,,,,,,,,,,,,,,,,,,
KPN12_S2_L001,NaN,NaN,NaN,NaN,NaN,yes_nonunique,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KPN13_S3_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KPN14_S4_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KPN15_S5_L001,NaN,yes_nonunique,yes_nonunique,NaN,yes_nonunique,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KPNH_S7_L001,NaN,NaN,NaN,NaN,NaN,yes_nonunique,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KPNI_S8_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KPNJ_S2_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KPNK_S1_L001,NaN,yes_nonunique,yes_nonunique,NaN,yes_nonunique,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
yeah= pd.concat([yes, yes_nonunique], axis=1)
yeah

,A7J11_01233+.assembled,aac_3__II-.assembled,aac_6___Ib+.assembled,aadA-.assembled,aadA1+.assembled,aadA2+.assembled,ant_2____Ia.assembled,aphA16.assembled,aph_3___Ia.assembled,aph_3___XV.assembled,...,qnrS-.assembled,sat2+.assembled,sul1.assembled,sul2.assembled,tet_C_.assembled,acrR.assembled,gyrA.assembled,ompK36.assembled,ompK37.assembled,ramR.assembled
samples,,,,,,,,,,,,,,,,,,,,,
KPN12_S2_L001,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,yes,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KPN13_S3_L001,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KPN14_S4_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KPN15_S5_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KPNH_S7_L001,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,yes,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KPNI_S8_L001,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KPNJ_S2_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KPNK_S1_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [89]:
yeah_column=yeah.stack()
yeah_column

samples
KPN12_S2_L001  aac_6___Ib+.assembled              yes
               aph_3___Ia.assembled               yes
               bla-_6.assembled                   yes
               blaKPC_-.assembled                 yes
               blaTEM_-.assembled                 yes
                                            ...
KPNK_S1_L001   aac_3__II-.assembled     yes_nonunique
               aac_6___Ib+.assembled    yes_nonunique
               aadA1+.assembled         yes_nonunique
               bla-_12.assembled        yes_nonunique
               blaTEM_-.assembled       yes_nonunique
Length: 151, dtype: object

In [90]:
yeah_column.index

MultiIndex([('KPN12_S2_L001', 'aac_6___Ib+.assembled'),
            ('KPN12_S2_L001',  'aph_3___Ia.assembled'),
            ('KPN12_S2_L001',      'bla-_6.assembled'),
            ('KPN12_S2_L001',    'blaKPC_-.assembled'),
            ('KPN12_S2_L001',    'blaTEM_-.assembled'),
            ('KPN12_S2_L001',       'catA1.assembled'),
            ('KPN12_S2_L001',      'dfrA12.assembled'),
            ('KPN12_S2_L001',     'fosA-_1.assembled'),
            ('KPN12_S2_L001',      'mph_A_.assembled'),
            ('KPN12_S2_L001',       'oqxA-.assembled'),
            ...
            ( 'KPNK_S1_L001',       'sat2+.assembled'),
            ( 'KPNK_S1_L001',        'sul1.assembled'),
            ( 'KPNK_S1_L001',        'sul2.assembled'),
            ( 'KPNK_S1_L001',        'acrR.assembled'),
            ( 'KPNK_S1_L001',      'ompK37.assembled'),
            ( 'KPNK_S1_L001',  'aac_3__II-.assembled'),
            ( 'KPNK_S1_L001', 'aac_6___Ib+.assembled'),
            ( 'KPNK_S1_L001',      'aadA1+.assembled'),
            ( 'KPNK_S1_L001',     'bla-_12.assembled'),
            ( 'KPNK_S1_L001',    'blaTEM_-.assembled')],
           names=['samples', None], length=151)

In [91]:
yeah_column_df = yeah_column.reset_index(level=[0,1])
yeah_column_df

           samples                level_1              0
0    KPN12_S2_L001  aac_6___Ib+.assembled            yes
1    KPN12_S2_L001   aph_3___Ia.assembled            yes
2    KPN12_S2_L001       bla-_6.assembled            yes
3    KPN12_S2_L001     blaKPC_-.assembled            yes
4    KPN12_S2_L001     blaTEM_-.assembled            yes
..             ...                    ...            ...
146   KPNK_S1_L001   aac_3__II-.assembled  yes_nonunique
147   KPNK_S1_L001  aac_6___Ib+.assembled  yes_nonunique
148   KPNK_S1_L001       aadA1+.assembled  yes_nonunique
149   KPNK_S1_L001      bla-_12.assembled  yes_nonunique
150   KPNK_S1_L001     blaTEM_-.assembled  yes_nonunique

[151 rows x 3 columns]

In [92]:
fixed_level1=yeah_column_df.level_1.str.rstrip('.assembled')
fixed_level2=pd.DataFrame(fixed_level1)
fixed_level2

         level_1
0    aac_6___Ib+
1      aph_3___I
2         bla-_6
3       blaKPC_-
4       blaTEM_-
..           ...
146   aac_3__II-
147  aac_6___Ib+
148       aadA1+
149      bla-_12
150     blaTEM_-

[151 rows x 1 columns]

In [93]:
yeah_column_df['level_1']=fixed_level2['level_1']
yeah_column_df

           samples      level_1              0
0    KPN12_S2_L001  aac_6___Ib+            yes
1    KPN12_S2_L001    aph_3___I            yes
2    KPN12_S2_L001       bla-_6            yes
3    KPN12_S2_L001     blaKPC_-            yes
4    KPN12_S2_L001     blaTEM_-            yes
..             ...          ...            ...
146   KPNK_S1_L001   aac_3__II-  yes_nonunique
147   KPNK_S1_L001  aac_6___Ib+  yes_nonunique
148   KPNK_S1_L001       aadA1+  yes_nonunique
149   KPNK_S1_L001      bla-_12  yes_nonunique
150   KPNK_S1_L001     blaTEM_-  yes_nonunique

[151 rows x 3 columns]

In [94]:
#####----------------------------------> data frame 1 ---> assembled arreglados!!
yeah_column_arreglada=yeah_column_df.set_index(['samples', 'level_1'])
yeah_column_arreglada=yeah_column_arreglada.rename(columns = {0:'yes/yes_nonunique'}, inplace = False)
yeah_column_arreglada

                          yes/yes_nonunique
samples       level_1
KPN12_S2_L001 aac_6___Ib+               yes
              aph_3___I                 yes
              bla-_6                    yes
              blaKPC_-                  yes
              blaTEM_-                  yes
...                                     ...
KPNK_S1_L001  aac_3__II-      yes_nonunique
              aac_6___Ib+     yes_nonunique
              aadA1+          yes_nonunique
              bla-_12         yes_nonunique
              blaTEM_-        yes_nonunique

[151 rows x 1 columns]

In [95]:
##### agroupment of the ".ctq_cov" data 
gene_id=datos.columns.str.find(".pct_id")
gene_id

Int64Index([-1, -1, 12, -1, -1, -1, 10, -1, -1, -1,
            ...
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
           dtype='int64', length=232)

In [96]:
ID=gene_id != -1
ID

array([False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [97]:
gene_identification=datos.iloc[:,ID]
gene_identification

,A7J11_01233+.pct_id,aac_3__II-.pct_id,aac_6___Ib+.pct_id,aadA-.pct_id,aadA1+.pct_id,aadA2+.pct_id,ant_2____Ia.pct_id,aphA16.pct_id,aph_3___Ia.pct_id,aph_3___XV.pct_id,...,mph_E_.pct_id,msr_E_.pct_id,oqxA-.pct_id,oqxB-.pct_id,qacE-.pct_id,qnrS-.pct_id,sat2+.pct_id,sul1.pct_id,sul2.pct_id,tet_C_.pct_id
samples,,,,,,,,,,,,,,,,,,,,,
KPN12_S2_L001,99.83,NaN,100.00,NaN,NaN,99.87,NaN,NaN,100.0,NaN,...,NaN,NaN,100.00,100.00,100.0,NaN,NaN,100.00,NaN,NaN
KPN13_S3_L001,99.65,NaN,99.82,NaN,NaN,NaN,NaN,NaN,NaN,100.0,...,NaN,NaN,99.57,99.71,NaN,100.0,NaN,NaN,NaN,NaN
KPN14_S4_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,...,NaN,NaN,99.66,99.43,100.0,NaN,NaN,100.00,NaN,100.0
KPN15_S5_L001,99.83,100.00,100.00,91.74,99.87,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,99.74,99.90,100.0,NaN,100.0,100.00,100.0,NaN
KPNH_S7_L001,99.83,NaN,100.00,NaN,NaN,100.00,NaN,NaN,100.0,NaN,...,NaN,NaN,100.00,100.00,100.0,NaN,NaN,100.00,NaN,NaN
KPNI_S8_L001,99.65,99.76,99.82,NaN,100.00,NaN,100.0,99.61,NaN,100.0,...,NaN,NaN,99.57,99.71,NaN,100.0,NaN,99.75,100.0,NaN
KPNJ_S2_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,...,NaN,NaN,99.66,99.43,100.0,NaN,NaN,100.00,NaN,100.0
KPNK_S1_L001,99.83,100.00,100.00,91.86,99.87,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,99.74,99.90,100.0,NaN,100.0,100.00,100.0,NaN

In [98]:
gene_identification_df=gene_identification.stack()
gene_identification_df

samples
KPN12_S2_L001  A7J11_01233+.pct_id     99.83
               aac_6___Ib+.pct_id     100.00
               aadA2+.pct_id           99.87
               aph_3___Ia.pct_id      100.00
               bla-_6.pct_id           99.88
                                       ...
KPNK_S1_L001   oqxB-.pct_id            99.90
               qacE-.pct_id           100.00
               sat2+.pct_id           100.00
               sul1.pct_id            100.00
               sul2.pct_id            100.00
Length: 155, dtype: float64

In [99]:
gene_identification_df = gene_identification_df.reset_index(level=[0,1])
gene_identification_df

           samples              level_1       0
0    KPN12_S2_L001  A7J11_01233+.pct_id   99.83
1    KPN12_S2_L001   aac_6___Ib+.pct_id  100.00
2    KPN12_S2_L001        aadA2+.pct_id   99.87
3    KPN12_S2_L001    aph_3___Ia.pct_id  100.00
4    KPN12_S2_L001        bla-_6.pct_id   99.88
..             ...                  ...     ...
150   KPNK_S1_L001         oqxB-.pct_id   99.90
151   KPNK_S1_L001         qacE-.pct_id  100.00
152   KPNK_S1_L001         sat2+.pct_id  100.00
153   KPNK_S1_L001          sul1.pct_id  100.00
154   KPNK_S1_L001          sul2.pct_id  100.00

[155 rows x 3 columns]

In [100]:
fixed_ID_level1_df=gene_identification_df.level_1.str.rstrip('.pct_id')
fixed_ID_level1_df=pd.DataFrame(fixed_ID_level1_df)
fixed_ID_level1_df

          level_1
0    A7J11_01233+
1     aac_6___Ib+
2          aadA2+
3      aph_3___Ia
4          bla-_6
..            ...
150         oqxB-
151         qacE-
152         sat2+
153          sul1
154          sul2

[155 rows x 1 columns]

In [101]:
gene_identification_df['level_1']=fixed_ID_level1_df['level_1']
gene_identification_df

           samples       level_1       0
0    KPN12_S2_L001  A7J11_01233+   99.83
1    KPN12_S2_L001   aac_6___Ib+  100.00
2    KPN12_S2_L001        aadA2+   99.87
3    KPN12_S2_L001    aph_3___Ia  100.00
4    KPN12_S2_L001        bla-_6   99.88
..             ...           ...     ...
150   KPNK_S1_L001         oqxB-   99.90
151   KPNK_S1_L001         qacE-  100.00
152   KPNK_S1_L001         sat2+  100.00
153   KPNK_S1_L001          sul1  100.00
154   KPNK_S1_L001          sul2  100.00

[155 rows x 3 columns]

In [102]:
#####----------------------------------> data frame 2 ---> identificacion de genes arreglados!!
gene_identification_fixed=gene_identification_df.set_index(['samples', 'level_1'])
gene_identification_fixed=gene_identification_fixed.rename(columns = {0:'%_ID'}, inplace = False)
gene_identification_fixed

                              %_ID
samples       level_1
KPN12_S2_L001 A7J11_01233+   99.83
              aac_6___Ib+   100.00
              aadA2+         99.87
              aph_3___Ia    100.00
              bla-_6         99.88
...                            ...
KPNK_S1_L001  oqxB-          99.90
              qacE-         100.00
              sat2+         100.00
              sul1          100.00
              sul2          100.00

[155 rows x 1 columns]

In [103]:
##### ------------------------------------------------>  agroupment of the ".ctq_cov" data 
coverage=datos.columns.str.find(".ctg_cov")
coverage

Int64Index([-1, -1, -1, 12, -1, -1, -1, 10, -1, -1,
            ...
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
           dtype='int64', length=232)

In [104]:
CO=coverage != -1
CO

array([False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [105]:
cover=datos.iloc[:,CO]
cover ###----> it shows the locus that have .ctg_cov suffix with a value (if it has a value on it)

,A7J11_01233+.ctg_cov,aac_3__II-.ctg_cov,aac_6___Ib+.ctg_cov,aadA-.ctg_cov,aadA1+.ctg_cov,aadA2+.ctg_cov,ant_2____Ia.ctg_cov,aphA16.ctg_cov,aph_3___Ia.ctg_cov,aph_3___XV.ctg_cov,...,mph_E_.ctg_cov,msr_E_.ctg_cov,oqxA-.ctg_cov,oqxB-.ctg_cov,qacE-.ctg_cov,qnrS-.ctg_cov,sat2+.ctg_cov,sul1.ctg_cov,sul2.ctg_cov,tet_C_.ctg_cov
samples,,,,,,,,,,,,,,,,,,,,,
KPN12_S2_L001,51.8,NaN,46.5,NaN,NaN,36.5,NaN,NaN,21.0,NaN,...,NaN,NaN,20.5,28.6,20.4,NaN,NaN,33.6,NaN,NaN
KPN13_S3_L001,37.7,NaN,41.0,NaN,NaN,NaN,NaN,NaN,NaN,19.0,...,NaN,NaN,24.7,28.3,NaN,39.2,NaN,NaN,NaN,NaN
KPN14_S4_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.1,NaN,...,NaN,NaN,17.7,19.1,17.9,NaN,NaN,18.4,NaN,19.1
KPN15_S5_L001,82.3,98.8,78.4,57.4,173.0,NaN,NaN,NaN,NaN,NaN,...,12.2,15.9,17.9,22.9,52.5,NaN,24.3,86.9,69.7,NaN
KPNH_S7_L001,35.9,NaN,40.9,NaN,NaN,36.6,NaN,NaN,18.6,NaN,...,NaN,NaN,22.5,23.2,24.8,NaN,NaN,43.8,NaN,NaN
KPNI_S8_L001,30.3,2.0,34.0,NaN,2.7,NaN,1.9,2.0,NaN,15.5,...,NaN,NaN,24.4,27.7,NaN,35.0,NaN,2.1,2.7,NaN
KPNJ_S2_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.4,NaN,...,NaN,NaN,30.6,37.4,29.9,NaN,NaN,38.6,NaN,44.6
KPNK_S1_L001,111.8,151.5,165.7,141.0,271.4,NaN,NaN,NaN,NaN,NaN,...,27.8,38.8,29.7,39.2,94.7,NaN,29.3,166.3,139.6,NaN

In [107]:
cover_filtrated=cover[cover>10]  ###----> sort the values coverage higher than 10 
cover_filtrated

,A7J11_01233+.ctg_cov,aac_3__II-.ctg_cov,aac_6___Ib+.ctg_cov,aadA-.ctg_cov,aadA1+.ctg_cov,aadA2+.ctg_cov,ant_2____Ia.ctg_cov,aphA16.ctg_cov,aph_3___Ia.ctg_cov,aph_3___XV.ctg_cov,...,mph_E_.ctg_cov,msr_E_.ctg_cov,oqxA-.ctg_cov,oqxB-.ctg_cov,qacE-.ctg_cov,qnrS-.ctg_cov,sat2+.ctg_cov,sul1.ctg_cov,sul2.ctg_cov,tet_C_.ctg_cov
samples,,,,,,,,,,,,,,,,,,,,,
KPN12_S2_L001,51.8,NaN,46.5,NaN,NaN,36.5,NaN,NaN,21.0,NaN,...,NaN,NaN,20.5,28.6,20.4,NaN,NaN,33.6,NaN,NaN
KPN13_S3_L001,37.7,NaN,41.0,NaN,NaN,NaN,NaN,NaN,NaN,19.0,...,NaN,NaN,24.7,28.3,NaN,39.2,NaN,NaN,NaN,NaN
KPN14_S4_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.1,NaN,...,NaN,NaN,17.7,19.1,17.9,NaN,NaN,18.4,NaN,19.1
KPN15_S5_L001,82.3,98.8,78.4,57.4,173.0,NaN,NaN,NaN,NaN,NaN,...,12.2,15.9,17.9,22.9,52.5,NaN,24.3,86.9,69.7,NaN
KPNH_S7_L001,35.9,NaN,40.9,NaN,NaN,36.6,NaN,NaN,18.6,NaN,...,NaN,NaN,22.5,23.2,24.8,NaN,NaN,43.8,NaN,NaN
KPNI_S8_L001,30.3,NaN,34.0,NaN,NaN,NaN,NaN,NaN,NaN,15.5,...,NaN,NaN,24.4,27.7,NaN,35.0,NaN,NaN,NaN,NaN
KPNJ_S2_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.4,NaN,...,NaN,NaN,30.6,37.4,29.9,NaN,NaN,38.6,NaN,44.6
KPNK_S1_L001,111.8,151.5,165.7,141.0,271.4,NaN,NaN,NaN,NaN,NaN,...,27.8,38.8,29.7,39.2,94.7,NaN,29.3,166.3,139.6,NaN

In [108]:
final_coverage=cover_filtrated.stack()
final_coverage

samples
KPN12_S2_L001  A7J11_01233+.ctg_cov     51.8
               aac_6___Ib+.ctg_cov      46.5
               aadA2+.ctg_cov           36.5
               aph_3___Ia.ctg_cov       21.0
               bla-_6.ctg_cov           44.6
                                       ...
KPNK_S1_L001   oqxB-.ctg_cov            39.2
               qacE-.ctg_cov            94.7
               sat2+.ctg_cov            29.3
               sul1.ctg_cov            166.3
               sul2.ctg_cov            139.6
Length: 146, dtype: float64

In [109]:
final_coverage_df = final_coverage.reset_index(level=[0,1])
final_coverage_df

           samples               level_1      0
0    KPN12_S2_L001  A7J11_01233+.ctg_cov   51.8
1    KPN12_S2_L001   aac_6___Ib+.ctg_cov   46.5
2    KPN12_S2_L001        aadA2+.ctg_cov   36.5
3    KPN12_S2_L001    aph_3___Ia.ctg_cov   21.0
4    KPN12_S2_L001        bla-_6.ctg_cov   44.6
..             ...                   ...    ...
141   KPNK_S1_L001         oqxB-.ctg_cov   39.2
142   KPNK_S1_L001         qacE-.ctg_cov   94.7
143   KPNK_S1_L001         sat2+.ctg_cov   29.3
144   KPNK_S1_L001          sul1.ctg_cov  166.3
145   KPNK_S1_L001          sul2.ctg_cov  139.6

[146 rows x 3 columns]

In [110]:
fixed_level1_cover=final_coverage_df.level_1.str.rstrip('.ctg_cov')
fixed_level1_cover=pd.DataFrame(fixed_level1_cover)
fixed_level1_cover

          level_1
0    A7J11_01233+
1     aac_6___Ib+
2          aadA2+
3      aph_3___Ia
4          bla-_6
..            ...
141         oqxB-
142         qacE-
143         sat2+
144          sul1
145          sul2

[146 rows x 1 columns]

In [111]:
final_coverage_df['level_1']=fixed_level1_cover['level_1']
final_coverage_df

           samples       level_1      0
0    KPN12_S2_L001  A7J11_01233+   51.8
1    KPN12_S2_L001   aac_6___Ib+   46.5
2    KPN12_S2_L001        aadA2+   36.5
3    KPN12_S2_L001    aph_3___Ia   21.0
4    KPN12_S2_L001        bla-_6   44.6
..             ...           ...    ...
141   KPNK_S1_L001         oqxB-   39.2
142   KPNK_S1_L001         qacE-   94.7
143   KPNK_S1_L001         sat2+   29.3
144   KPNK_S1_L001          sul1  166.3
145   KPNK_S1_L001          sul2  139.6

[146 rows x 3 columns]

In [112]:
#####----------------------------------> data frame 2 ---> coverage arreglados!!
final_coverage_fixed=final_coverage_df.set_index(['samples', 'level_1'])
final_coverage_fixed=final_coverage_fixed.rename(columns = {0:'coverage'}, inplace = False)
final_coverage_fixed

                            coverage
samples       level_1
KPN12_S2_L001 A7J11_01233+      51.8
              aac_6___Ib+       46.5
              aadA2+            36.5
              aph_3___Ia        21.0
              bla-_6            44.6
...                              ...
KPNK_S1_L001  oqxB-             39.2
              qacE-             94.7
              sat2+             29.3
              sul1             166.3
              sul2             139.6

[146 rows x 1 columns]

In [113]:
database_anthony=pd.read_csv("/Users/felipedb/Documents/data/projects/training/taller_agrosavia/ariba_exercise/exercise_2_ncbi_acquired_genes_metadata.csv", sep=",")
database_anthony

,#allele,gene family,refseq nucleotide,class,subclass,refseq protein,genbank protein
0,NaN,aac(2')-IIa,NG_047225.1,AMINOGLYCOSIDE,KASUGAMYCIN,WP_063839881.1,BAM16262.1
1,NaN,aac(2')-IIb,NG_055672.1,AMINOGLYCOSIDE,KASUGAMYCIN,WP_071224044.1,APB03221.1
2,NaN,aac(2')-Ia,NG_047226.1,AMINOGLYCOSIDE,GENTAMICIN/TOBRAMCYIN,WP_004918308.1,AAA03550.1
3,NaN,aac(2')-Ib,NG_047227.1,AMINOGLYCOSIDE,GENTAMICIN/TOBRAMCYIN,WP_003881640.1,AAC44793.1
4,NaN,aac(2')-Ic,NG_047229.1,AMINOGLYCOSIDE,GENTAMICIN/TOBRAMCYIN,WP_003899880.1,AAB17563.1
...,...,...,...,...,...,...,...
7239,uhpT_W425R,uhpT,NaN,FOSFOMYCIN,FOSFOMYCIN,WP_001008722.1,CAG39240.1
7240,walK_L10F,walK,NaN,LIPOPEPTIDE,DAPTOMYCIN,WP_000871610.1,CAG39047.1
7241,walK_S221P,walK,NaN,LIPOPEPTIDE,DAPTOMYCIN,WP_000871610.1,CAG39047.1
7242,walK_R263C,walK,NaN,LIPOPEPTIDE,DAPTOMYCIN,WP_000871610.1,CAG39047.1
7243,yybT_I440S,yybT,NaN,LIPOPEPTIDE,DAPTOMYCIN,WP_002356022.1,AAO79895.1

In [114]:
NCBI_filtered = database_anthony[database_anthony["refseq nucleotide"].str.find("NG_")!=-1]
NCBI_filtered

,#allele,gene family,refseq nucleotide,class,subclass,refseq protein,genbank protein
0,NaN,aac(2')-IIa,NG_047225.1,AMINOGLYCOSIDE,KASUGAMYCIN,WP_063839881.1,BAM16262.1
1,NaN,aac(2')-IIb,NG_055672.1,AMINOGLYCOSIDE,KASUGAMYCIN,WP_071224044.1,APB03221.1
2,NaN,aac(2')-Ia,NG_047226.1,AMINOGLYCOSIDE,GENTAMICIN/TOBRAMCYIN,WP_004918308.1,AAA03550.1
3,NaN,aac(2')-Ib,NG_047227.1,AMINOGLYCOSIDE,GENTAMICIN/TOBRAMCYIN,WP_003881640.1,AAC44793.1
4,NaN,aac(2')-Ic,NG_047229.1,AMINOGLYCOSIDE,GENTAMICIN/TOBRAMCYIN,WP_003899880.1,AAB17563.1
...,...,...,...,...,...,...,...
7239,uhpT_W425R,uhpT,NaN,FOSFOMYCIN,FOSFOMYCIN,WP_001008722.1,CAG39240.1
7240,walK_L10F,walK,NaN,LIPOPEPTIDE,DAPTOMYCIN,WP_000871610.1,CAG39047.1
7241,walK_S221P,walK,NaN,LIPOPEPTIDE,DAPTOMYCIN,WP_000871610.1,CAG39047.1
7242,walK_R263C,walK,NaN,LIPOPEPTIDE,DAPTOMYCIN,WP_000871610.1,CAG39047.1
7243,yybT_I440S,yybT,NaN,LIPOPEPTIDE,DAPTOMYCIN,WP_002356022.1,AAO79895.1

In [115]:
ref_seq=datos.columns.str.find(".ref_seq")###----------------->reference sequence filtering from my samples
ref_seq

Int64Index([-1, 12, -1, -1, -1, 10, -1, -1, -1, 11,
            ...
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
           dtype='int64', length=232)

In [116]:
RF=ref_seq != -1
RF

array([False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [117]:
referenced=datos.iloc[:,RF]
referenced

,A7J11_01233+.ref_seq,aac_3__II-.ref_seq,aac_6___Ib+.ref_seq,aadA-.ref_seq,aadA1+.ref_seq,aadA2+.ref_seq,ant_2____Ia.ref_seq,aphA16.ref_seq,aph_3___Ia.ref_seq,aph_3___XV.ref_seq,...,mph_E_.ref_seq,msr_E_.ref_seq,oqxA-.ref_seq,oqxB-.ref_seq,qacE-.ref_seq,qnrS-.ref_seq,sat2+.ref_seq,sul1.ref_seq,sul2.ref_seq,tet_C_.ref_seq
samples,,,,,,,,,,,,,,,,,,,,,
KPN12_S2_L001,A7J11_01233.NG_047213.1,NaN,aac_6___Ib.NG_056043.1,NaN,NaN,aadA2.NG_051846.1,NaN,NaN,aph_3___Ia.NG_047430.1,NaN,...,NaN,NaN,oqxA.NG_048024.1,oqxB.NG_048025.1,qacEdelta1.NG_048042.1,NaN,NaN,sul1.NG_048082.1,NaN,NaN
KPN13_S3_L001,A7J11_01233.NG_047213.1,NaN,aac_6___Ib4.NG_051844.1,NaN,NaN,NaN,NaN,NaN,NaN,aph_3___XV.NG_052510.1,...,NaN,NaN,oqxA5.NG_050423.1,oqxB18.NG_050436.1,NaN,qnrS1.NG_050543.1,NaN,NaN,NaN,NaN
KPN14_S4_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,aph_3___Ia.NG_047430.1,NaN,...,NaN,NaN,oqxA10.NG_050418.1,oqxB22.NG_050441.1,qacEdelta1.NG_048042.1,NaN,NaN,sul1.NG_048082.1,NaN,tet_C_.NG_048177.1
KPN15_S5_L001,A7J11_01233.NG_047213.1,aac_3__IId.NG_047251.1,aac_6___Ib.NG_056043.1,aadA13.NG_052310.1,aadA1.NG_052536.1,NaN,NaN,NaN,NaN,NaN,...,mph_E_.NG_064660.1,msr_E_.NG_048007.1,oqxA6.NG_050424.1,oqxB20.NG_050439.1,qacEdelta1.NG_048042.1,NaN,sat2.NG_048068.1,sul1.NG_048081.1,sul2.NG_051852.1,NaN
KPNH_S7_L001,A7J11_01233.NG_047213.1,NaN,aac_6___Ib.NG_056043.1,NaN,NaN,aadA2.NG_047343.1,NaN,NaN,aph_3___Ia.NG_047430.1,NaN,...,NaN,NaN,oqxA.NG_048024.1,oqxB.NG_048025.1,qacEdelta1.NG_048042.1,NaN,NaN,sul1.NG_048082.1,NaN,NaN
KPNI_S8_L001,A7J11_01233.NG_047213.1,aac_3__IId.NG_047251.1,aac_6___Ib4.NG_051844.1,NaN,aadA8.NG_052405.1,NaN,ant_2____Ia.NG_052437.1,aphA16.NG_051908.1,NaN,aph_3___XV.NG_052510.1,...,NaN,NaN,oqxA5.NG_050423.1,oqxB18.NG_050436.1,NaN,qnrS1.NG_050543.1,NaN,sul1.NG_048089.1,sul2.NG_051852.1,NaN
KPNJ_S2_L001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,aph_3___Ia.NG_047430.1,NaN,...,NaN,NaN,oqxA10.NG_050418.1,oqxB22.NG_050441.1,qacEdelta1.NG_048042.1,NaN,NaN,sul1.NG_048082.1,NaN,tet_C_.NG_048177.1
KPNK_S1_L001,A7J11_01233.NG_047213.1,aac_3__IId.NG_047251.1,aac_6___Ib.NG_056043.1,aadA13.NG_052310.1,aadA1.NG_052536.1,NaN,NaN,NaN,NaN,NaN,...,mph_E_.NG_064660.1,msr_E_.NG_048007.1,oqxA6.NG_050424.1,oqxB20.NG_050439.1,qacEdelta1.NG_048042.1,NaN,sat2.NG_048068.1,sul1.NG_048081.1,sul2.NG_051852.1,NaN

In [118]:
NG=referenced.stack()
NG

samples
KPN12_S2_L001  A7J11_01233+.ref_seq    A7J11_01233.NG_047213.1
               aac_6___Ib+.ref_seq      aac_6___Ib.NG_056043.1
               aadA2+.ref_seq                aadA2.NG_051846.1
               aph_3___Ia.ref_seq       aph_3___Ia.NG_047430.1
               bla-_6.ref_seq           blaSHV_182.NG_050049.1
                                                ...
KPNK_S1_L001   oqxB-.ref_seq                oqxB20.NG_050439.1
               qacE-.ref_seq            qacEdelta1.NG_048042.1
               sat2+.ref_seq                  sat2.NG_048068.1
               sul1.ref_seq                   sul1.NG_048081.1
               sul2.ref_seq                   sul2.NG_051852.1
Length: 155, dtype: object

In [119]:
NG_separados=[".".join(i.split(".")[1:3]) for i in NG.values]
NG_separados

['NG_047213.1',
 'NG_056043.1',
 'NG_051846.1',
 'NG_047430.1',
 'NG_050049.1',
 'NG_049257.1',
 'NG_049830.1',
 'NG_050299.1',
 'NG_047587.1',
 'NG_052052.1',
 'NG_047689.1',
 'NG_051497.1',
 'NG_047985.1',
 'NG_048024.1',
 'NG_048025.1',
 'NG_048042.1',
 'NG_048082.1',
 'NG_047213.1',
 'NG_051844.1',
 'NG_052510.1',
 'NG_050590.1',
 'NG_050336.1',
 'NG_052052.1',
 'NG_056035.1',
 'NG_051497.1',
 'NG_050423.1',
 'NG_050436.1',
 'NG_050543.1',
 'NG_047430.1',
 'NG_050121.1',
 'NG_049762.1',
 'NG_050145.1',
 'NG_047587.1',
 'NG_051699.1',
 'NG_056035.1',
 'NG_047763.1',
 'NG_051497.1',
 'NG_050418.1',
 'NG_050441.1',
 'NG_048042.1',
 'NG_048082.1',
 'NG_048177.1',
 'NG_047213.1',
 'NG_047251.1',
 'NG_056043.1',
 'NG_052310.1',
 'NG_052536.1',
 'NG_056002.2',
 'NG_047466.1',
 'NG_047476.1',
 'NG_048580.1',
 'NG_048834.1',
 'NG_050105.1',
 'NG_049075.1',
 'NG_063835.1',
 'NG_048935.1',
 'NG_049326.1',
 'NG_049392.1',
 'NG_049830.1',
 'NG_050299.1',
 'NG_047559.1',
 'NG_047587.1',
 'NG_052455.1',
 'NG_051436.1',
 'NG_047676.1',
 'NG_047770.1',
 'NG_051497.1',
 'NG_064660.1',
 'NG_048007.1',
 'NG_050424.1',
 'NG_050439.1',
 'NG_048042.1',
 'NG_048068.1',
 'NG_048081.1',
 'NG_051852.1',
 'NG_047213.1',
 'NG_056043.1',
 'NG_047343.1',
 'NG_047430.1',
 'NG_050049.1',
 'NG_049257.1',
 'NG_049830.1',
 'NG_050299.1',
 'NG_047587.1',
 'NG_052052.1',
 'NG_047689.1',
 'NG_051497.1',
 'NG_047985.1',
 'NG_048024.1',
 'NG_048025.1',
 'NG_048042.1',
 'NG_048082.1',
 'NG_047213.1',
 'NG_047251.1',
 'NG_051844.1',
 'NG_052405.1',
 'NG_052437.1',
 'NG_051908.1',
 'NG_052510.1',
 'NG_050590.1',
 'NG_050336.1',
 'NG_052052.1',
 'NG_056035.1',
 'NG_051497.1',
 'NG_050423.1',
 'NG_050436.1',
 'NG_050543.1',
 'NG_048089.1',
 'NG_051852.1',
 'NG_047430.1',
 'NG_050121.1',
 'NG_049762.1',
 'NG_050145.1',
 'NG_047587.1',
 'NG_051699.1',
 'NG_056035.1',
 'NG_047763.1',
 'NG_051497.1',
 'NG_050418.1',
 'NG_050441.1',
 'NG_048042.1',
 'NG_048082.1',
 'NG_048177.1',
 'NG_047213.1',
 'NG_047251.1',
 'NG_056043.1',
 'NG_052310.1',
 'NG_052536.1',
 'NG_056002.2',
 'NG_047466.1',
 'NG_047476.1',
 'NG_048580.1',
 'NG_048834.1',
 'NG_050105.1',
 'NG_049075.1',
 'NG_048935.1',
 'NG_049326.1',
 'NG_049392.1',
 'NG_049830.1',
 'NG_050266.1',
 'NG_047559.1',
 'NG_047587.1',
 'NG_052455.1',
 'NG_051436.1',
 'NG_047676.1',
 'NG_047770.1',
 'NG_051497.1',
 'NG_064660.1',
 'NG_048007.1',
 'NG_050424.1',
 'NG_050439.1',
 'NG_048042.1',
 'NG_048068.1',
 'NG_048081.1',
 'NG_051852.1']

In [120]:
NG_arreglados=pd.DataFrame(NG_separados,index=NG.index)
NG_arreglados.columns=["refseq_nucleotide_accession"]
NG_arreglados

                                   refseq_nucleotide_accession
samples
KPN12_S2_L001 A7J11_01233+.ref_seq                 NG_047213.1
              aac_6___Ib+.ref_seq                  NG_056043.1
              aadA2+.ref_seq                       NG_051846.1
              aph_3___Ia.ref_seq                   NG_047430.1
              bla-_6.ref_seq                       NG_050049.1
...                                                        ...
KPNK_S1_L001  oqxB-.ref_seq                        NG_050439.1
              qacE-.ref_seq                        NG_048042.1
              sat2+.ref_seq                        NG_048068.1
              sul1.ref_seq                         NG_048081.1
              sul2.ref_seq                         NG_051852.1

[155 rows x 1 columns]

In [121]:
NG_arreglados_df = NG_arreglados.reset_index(level=[0,1])
NG_arreglados_df

           samples               level_1 refseq_nucleotide_accession
0    KPN12_S2_L001  A7J11_01233+.ref_seq                 NG_047213.1
1    KPN12_S2_L001   aac_6___Ib+.ref_seq                 NG_056043.1
2    KPN12_S2_L001        aadA2+.ref_seq                 NG_051846.1
3    KPN12_S2_L001    aph_3___Ia.ref_seq                 NG_047430.1
4    KPN12_S2_L001        bla-_6.ref_seq                 NG_050049.1
..             ...                   ...                         ...
150   KPNK_S1_L001         oqxB-.ref_seq                 NG_050439.1
151   KPNK_S1_L001         qacE-.ref_seq                 NG_048042.1
152   KPNK_S1_L001         sat2+.ref_seq                 NG_048068.1
153   KPNK_S1_L001          sul1.ref_seq                 NG_048081.1
154   KPNK_S1_L001          sul2.ref_seq                 NG_051852.1

[155 rows x 3 columns]

In [122]:
fixed_column_NG_arreglados_df=NG_arreglados_df.level_1.str.rstrip('.ref_seq')
fixed_column_NG_arreglados_df=pd.DataFrame(fixed_column_NG_arreglados_df)
fixed_column_NG_arreglados_df

          level_1
0    A7J11_01233+
1     aac_6___Ib+
2          aadA2+
3      aph_3___Ia
4          bla-_6
..            ...
150         oqxB-
151         qacE-
152         sat2+
153          sul1
154          sul2

[155 rows x 1 columns]

In [123]:
NG_arreglados_df['level_1']=fixed_column_NG_arreglados_df['level_1']
NG_arreglados_df

           samples       level_1 refseq_nucleotide_accession
0    KPN12_S2_L001  A7J11_01233+                 NG_047213.1
1    KPN12_S2_L001   aac_6___Ib+                 NG_056043.1
2    KPN12_S2_L001        aadA2+                 NG_051846.1
3    KPN12_S2_L001    aph_3___Ia                 NG_047430.1
4    KPN12_S2_L001        bla-_6                 NG_050049.1
..             ...           ...                         ...
150   KPNK_S1_L001         oqxB-                 NG_050439.1
151   KPNK_S1_L001         qacE-                 NG_048042.1
152   KPNK_S1_L001         sat2+                 NG_048068.1
153   KPNK_S1_L001          sul1                 NG_048081.1
154   KPNK_S1_L001          sul2                 NG_051852.1

[155 rows x 3 columns]

In [124]:
#####----------------------------------> data frame 3 ---> NG arreglados!!
NG_fixed=NG_arreglados_df.set_index(['samples', 'level_1'])
NG_fixed

                           refseq_nucleotide_accession
samples       level_1
KPN12_S2_L001 A7J11_01233+                 NG_047213.1
              aac_6___Ib+                  NG_056043.1
              aadA2+                       NG_051846.1
              aph_3___Ia                   NG_047430.1
              bla-_6                       NG_050049.1
...                                                ...
KPNK_S1_L001  oqxB-                        NG_050439.1
              qacE-                        NG_048042.1
              sat2+                        NG_048068.1
              sul1                         NG_048081.1
              sul2                         NG_051852.1

[155 rows x 1 columns]

In [125]:
### Union entre las mutaciones y la base de datos:
mutaciones_finales=mutation_result_df.join(database_anthony.set_index("#allele"),on="level_1")
mutaciones_finales

                           mutation_result gene family refseq nucleotide  \
samples       level_1
KPN12_S2_L001 acrR_F172S               yes         NaN               NaN
              acrR_F197I               yes         NaN               NaN
              acrR_G164A               yes         NaN               NaN
              acrR_K201M               yes         NaN               NaN
              acrR_L195V               yes         NaN               NaN
...                                    ...         ...               ...
KPNK_S1_L001  ompK36_L59V              yes         NaN               NaN
              ompK36_N218H             yes         NaN               NaN
              ompK36_N49S              yes         NaN               NaN
              ompK37_I128M             yes         NaN               NaN
              ompK37_I70M              yes         NaN               NaN

                           class subclass refseq protein genbank protein
samples       level_1
KPN12_S2_L001 acrR_F172S     NaN      NaN            NaN             NaN
              acrR_F197I     NaN      NaN            NaN             NaN
              acrR_G164A     NaN      NaN            NaN             NaN
              acrR_K201M     NaN      NaN            NaN             NaN
              acrR_L195V     NaN      NaN            NaN             NaN
...                          ...      ...            ...             ...
KPNK_S1_L001  ompK36_L59V    NaN      NaN            NaN             NaN
              ompK36_N218H   NaN      NaN            NaN             NaN
              ompK36_N49S    NaN      NaN            NaN             NaN
              ompK37_I128M   NaN      NaN            NaN             NaN
              ompK37_I70M    NaN      NaN            NaN             NaN

[155 rows x 7 columns]

In [126]:
tabla_final_NCBI=database_anthony[database_anthony['refseq nucleotide'].isin(NG_separados)]
tabla_final_NCBI.to_csv("tabla_final_NCBI.csv")
tabla_final_NCBI

,#allele,gene family,refseq nucleotide,class,subclass,refseq protein,genbank protein
16,NaN,aac(3)-IId,NG_047251.1,AMINOGLYCOSIDE,GENTAMICIN,WP_000557454.1,AAN87703.1
241,NaN,aac(6')-Ib,NG_056043.1,AMINOGLYCOSIDE,AMIKACIN/KANAMYCIN/TOBRAMYCIN,WP_063840280.1,KSL18989.2
279,aac(6')-Ib4,aac(6')-Ib,NG_051844.1,AMINOGLYCOSIDE,GENTAMICIN,WP_003159191.1,AAF72941.1
377,NaN,aadA1,NG_052536.1,AMINOGLYCOSIDE,STREPTOMYCIN,WP_046622360.1,KKJ21274.1
394,NaN,aadA13,NG_052310.1,AMINOGLYCOSIDE,STREPTOMYCIN,WP_071846269.1,AGY30809.1
...,...,...,...,...,...,...,...
5892,NaN,sul1,NG_048081.1,SULFONAMIDE,SULFONAMIDE,WP_000259032.1,CAA33123.1
5902,NaN,sul2,NG_051852.1,SULFONAMIDE,SULFONAMIDE,WP_001043260.1,AAK64592.1
6025,NaN,tet(C),NG_048177.1,TETRACYCLINE,TETRACYCLINE,WP_001297013.1,AAK97755.1
6512,NaN,NaN,NG_052052.1,AMINOGLYCOSIDE,GENTAMICIN,WP_071593228.1,BAK79091.1
6513,NaN,NaN,NG_047213.1,AMINOGLYCOSIDE,GENTAMICIN,WP_063838853.1,CAE48335.2

In [127]:
resultado_final=NG_fixed.join(tabla_final_NCBI.set_index("refseq nucleotide"),on="refseq_nucleotide_accession")
resultado_final

                           refseq_nucleotide_accession     #allele  \
samples       level_1
KPN12_S2_L001 A7J11_01233+                 NG_047213.1         NaN
              aac_6___Ib+                  NG_056043.1         NaN
              aadA2+                       NG_051846.1         NaN
              aph_3___Ia                   NG_047430.1         NaN
              bla-_6                       NG_050049.1  blaSHV-182
...                                                ...         ...
KPNK_S1_L001  oqxB-                        NG_050439.1      oqxB20
              qacE-                        NG_048042.1  qacEdelta1
              sat2+                        NG_048068.1         NaN
              sul1                         NG_048081.1         NaN
              sul2                         NG_051852.1         NaN

                           gene family                class  \
samples       level_1
KPN12_S2_L001 A7J11_01233+         NaN       AMINOGLYCOSIDE
              aac_6___Ib+   aac(6')-Ib       AMINOGLYCOSIDE
              aadA2+             aadA2       AMINOGLYCOSIDE
              aph_3___Ia    aph(3')-Ia       AMINOGLYCOSIDE
              bla-_6            blaSHV          BETA-LACTAM
...                                ...                  ...
KPNK_S1_L001  oqxB-               oqxB   PHENICOL/QUINOLONE
              qacE-               qacE  QUATERNARY AMMONIUM
              sat2+               sat2       STREPTOTHRICIN
              sul1                sul1          SULFONAMIDE
              sul2                sul2          SULFONAMIDE

                                                 subclass  refseq protein  \
samples       level_1
KPN12_S2_L001 A7J11_01233+                     GENTAMICIN  WP_063838853.1
              aac_6___Ib+   AMIKACIN/KANAMYCIN/TOBRAMYCIN  WP_063840280.1
              aadA2+                         STREPTOMYCIN  WP_001261740.1
              aph_3___Ia                        KANAMYCIN  WP_000018329.1
              bla-_6                          BETA-LACTAM  WP_063864660.1
...                                                   ...             ...
KPNK_S1_L001  oqxB-                    PHENICOL/QUINOLONE  WP_021312368.1
              qacE-                   QUATERNARY AMMONIUM  WP_000679427.1
              sat2+                        STREPTOTHRICIN  WP_000704156.1
              sul1                            SULFONAMIDE  WP_000259032.1
              sul2                            SULFONAMIDE  WP_001043260.1

                           genbank protein
samples       level_1
KPN12_S2_L001 A7J11_01233+      CAE48335.2
              aac_6___Ib+       KSL18989.2
              aadA2+            AAF87686.1
              aph_3___Ia        CAA23656.1
              bla-_6            AJO16042.1
...                                    ...
KPNK_S1_L001  oqxB-             AGZ20241.1
              qacE-             AAC44316.1
              sat2+             CAA34124.1
              sul1              CAA33123.1
              sul2              AAK64592.1

[155 rows x 7 columns]

In [128]:
resultado_integrated= pd.concat([resultado_final, yeah_column_arreglada], axis=1)
resultado_integrated=pd.concat([resultado_integrated, final_coverage_fixed], axis=1)
resultado_integrated=pd.concat([resultado_integrated, gene_identification_fixed], axis=1)
resultado_integrated=pd.concat([resultado_integrated, mutation_result_df], axis=1)
resultado_integrated

                           refseq_nucleotide_accession     #allele  \
samples       level_1
KPN12_S2_L001 A7J11_01233+                 NG_047213.1         NaN
              aac_6___Ib+                  NG_056043.1         NaN
              aadA2+                       NG_051846.1         NaN
              acrR                                 NaN         NaN
              acrR_F172S                           NaN         NaN
...                                                ...         ...
KPNK_S1_L001  oqxB-                        NG_050439.1      oqxB20
              qacE-                        NG_048042.1  qacEdelta1
              sat2+                        NG_048068.1         NaN
              sul1                         NG_048081.1         NaN
              sul2                         NG_051852.1         NaN

                           gene family                class  \
samples       level_1
KPN12_S2_L001 A7J11_01233+         NaN       AMINOGLYCOSIDE
              aac_6___Ib+   aac(6')-Ib       AMINOGLYCOSIDE
              aadA2+             aadA2       AMINOGLYCOSIDE
              acrR                 NaN                  NaN
              acrR_F172S           NaN                  NaN
...                                ...                  ...
KPNK_S1_L001  oqxB-               oqxB   PHENICOL/QUINOLONE
              qacE-               qacE  QUATERNARY AMMONIUM
              sat2+               sat2       STREPTOTHRICIN
              sul1                sul1          SULFONAMIDE
              sul2                sul2          SULFONAMIDE

                                                 subclass  refseq protein  \
samples       level_1
KPN12_S2_L001 A7J11_01233+                     GENTAMICIN  WP_063838853.1
              aac_6___Ib+   AMIKACIN/KANAMYCIN/TOBRAMYCIN  WP_063840280.1
              aadA2+                         STREPTOMYCIN  WP_001261740.1
              acrR                                    NaN             NaN
              acrR_F172S                              NaN             NaN
...                                                   ...             ...
KPNK_S1_L001  oqxB-                    PHENICOL/QUINOLONE  WP_021312368.1
              qacE-                   QUATERNARY AMMONIUM  WP_000679427.1
              sat2+                        STREPTOTHRICIN  WP_000704156.1
              sul1                            SULFONAMIDE  WP_000259032.1
              sul2                            SULFONAMIDE  WP_001043260.1

                           genbank protein yes/yes_nonunique  coverage  \
samples       level_1
KPN12_S2_L001 A7J11_01233+      CAE48335.2               NaN      51.8
              aac_6___Ib+       KSL18989.2               yes      46.5
              aadA2+            AAF87686.1     yes_nonunique      36.5
              acrR                     NaN               yes       NaN
              acrR_F172S               NaN               NaN       NaN
...                                    ...               ...       ...
KPNK_S1_L001  oqxB-             AGZ20241.1               yes      39.2
              qacE-             AAC44316.1               yes      94.7
              sat2+             CAA34124.1               yes      29.3
              sul1              CAA33123.1               yes     166.3
              sul2              AAK64592.1               yes     139.6

                              %_ID mutation_result
samples       level_1
KPN12_S2_L001 A7J11_01233+   99.83             NaN
              aac_6___Ib+   100.00             NaN
              aadA2+         99.87             NaN
              acrR             NaN             NaN
              acrR_F172S       NaN             yes
...                            ...             ...
KPNK_S1_L001  oqxB-          99.90             NaN
              qacE-         100.00             NaN
              sat2+         100.00             NaN
              sul1          100.00             NaN
              sul2          100.00             NaN

[347 rows x 11 columns]

In [129]:
resultado_integrated.to_csv("Klebsiella_resultado_integrated.csv")####---> final output

In [130]:
mutaciones_finales.to_csv("Klebsiella_resultado_mutaciones_integrated.csv")####---> final output

In [131]:
mutaciones_finales

                           mutation_result gene family refseq nucleotide  \
samples       level_1
KPN12_S2_L001 acrR_F172S               yes         NaN               NaN
              acrR_F197I               yes         NaN               NaN
              acrR_G164A               yes         NaN               NaN
              acrR_K201M               yes         NaN               NaN
              acrR_L195V               yes         NaN               NaN
...                                    ...         ...               ...
KPNK_S1_L001  ompK36_L59V              yes         NaN               NaN
              ompK36_N218H             yes         NaN               NaN
              ompK36_N49S              yes         NaN               NaN
              ompK37_I128M             yes         NaN               NaN
              ompK37_I70M              yes         NaN               NaN

                           class subclass refseq protein genbank protein
samples       level_1
KPN12_S2_L001 acrR_F172S     NaN      NaN            NaN             NaN
              acrR_F197I     NaN      NaN            NaN             NaN
              acrR_G164A     NaN      NaN            NaN             NaN
              acrR_K201M     NaN      NaN            NaN             NaN
              acrR_L195V     NaN      NaN            NaN             NaN
...                          ...      ...            ...             ...
KPNK_S1_L001  ompK36_L59V    NaN      NaN            NaN             NaN
              ompK36_N218H   NaN      NaN            NaN             NaN
              ompK36_N49S    NaN      NaN            NaN             NaN
              ompK37_I128M   NaN      NaN            NaN             NaN
              ompK37_I70M    NaN      NaN            NaN             NaN

[155 rows x 7 columns]